### ISSUE TITLE
In vuestorefront , After selected stripe payment option (did not display the input payment details like card-number..etc)

### ISSUE THREAD

**Issue by manojibcarockers** [develodesign/vsf-payment-stripe#18]
I'm trying stripe-payment integration in Vuestorefront,
I follow the steps through this link: "https://github.com/develodesign/vsf-payment-stripe"
But
The strip payment option is displayed correctly on Vuestorefront, but after the selected stripe payment option (it did not display the required input payment details, such as card number ..etc)
How to solve it?

**Comment by manojibcarockers** [comment]
I solved the issue by using stripe-Api (public key)

**Comment by rain2o** [comment]
It would be helpful to notate in the README that the `apiKey` should be the Public Key to avoid any confusion.
