### ISSUE TITLE
Doc issue: Need set correct path to extension bootstrap.

### ISSUE THREAD

**Issue by dimasch** [develodesign/vsf-payment-stripe#2]
@collymore Luke, i can fixed it, i prepare commit, but i have't permissions for this repo...

![2018-07-10_00-42-38](https://user-images.githubusercontent.com/414067/42474985-4f6b91ca-83da-11e8-9090-01da3095594b.png)

**Comment by collymore** [comment]
I've just merged a PR to fix this, I've also fixed the team permissions
