### ISSUE TITLE
Unable to place order using stripe payment

### ISSUE THREAD

**Issue by razzul** [develodesign/vsf-payment-stripe#23]
<div class="text-center p-3">
          <span class="border-wrap"><img src="/razzul/img/blob/master/order-failed-stripe.gif?raw=true" alt="order-failed-stripe.gif"></span>
      </div>

**Comment by dimasch** [comment]
@razzul Thanks, for feedback.

**Comment by dimasch** [comment]
@razzul Fixed in #24 in `v2.2.0` tag
Thanks.
