### ISSUE TITLE
Issue with Place Order button stuck

### ISSUE THREAD

**Issue by rohitrics** [develodesign/vsf-payment-stripe#39]
After installing and setup all its not creating order. Its got stuck while clicking on Place Order.
No console errors are there.
Please check the screenshot : http://prntscr.com/q8cqfp

**Comment by vineeth030** [comment]
1. Check your PM2 logs.
2. There is a small change in doc of vsf_payment_stripe
Instead of this:
`"stripe": {
    "apiKey": "my_example_api_key",
    "backend_platform": "magento2",
    "paymentMethodCode": "stripe_payments"
}`
Use this:
`"stripe": {
    "apiKey": "my_example_api_key",
    "backendPlatform": "magento2",
    "paymentMethodCode": "stripe_payments"
}`

**Comment by dimasch** [comment]
@vineeth030 Thanks!
Merged readme PR.
